### ISSUE TITLE
添加图片时崩溃

### ISSUE THREAD

**Issue by iseki0** [xtomcom/sm-ms-app#1]
添加第一张正常，第二张崩溃
![截屏_20170816_153243.png](https://i.loli.net/2017/08/16/5993f52b2a3b3.png)
报错：
http://paste.ubuntu.com/25324225/

**Comment by iseki0** [comment]
刚看了看，图片是webp格式的。

**Comment by EGOISTK21** [comment]
图床本身不支持webp，下个版本更新的时候我会给一些特殊格式做一下转换。

## SM.MS目前支持的格式
- jpg
- png
- gif
